# Generated by Django 3.2.18 on 2023-04-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.DecimalField(decimal_places=2, max_digits=20)),
                ('active_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.activeingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('active_ingredients', models.ManyToManyField(blank=True, through='blog.Content', to='blog.ActiveIngredient')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.form')),
                ('ingredients', models.ManyToManyField(blank=True, to='blog.Ingredient')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('product_url', models.URLField(max_length=2048)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.shop')),
                ('supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.supplement')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='supplement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.supplement'),
        ),
        migrations.AddField(
            model_name='content',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.unit'),
        ),
    ]
