# Generated by Django 3.2.16 on 2023-05-03 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.DecimalField(decimal_places=2, max_digits=20)),
                ('active_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.activeingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_net', models.DecimalField(decimal_places=2, max_digits=19)),
                ('tax', models.IntegerField(choices=[(7, '7%'), (19, '19%')], default=19)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=2048)),
                ('min_order_value_free_shipping', models.DecimalField(decimal_places=2, max_digits=20)),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('daily_dose', models.DecimalField(decimal_places=2, max_digits=20)),
                ('intake_note', models.TextField(blank=True, null=True)),
                ('active_ingredients', models.ManyToManyField(blank=True, through='blog.Content', to='blog.ActiveIngredient')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.form')),
                ('ingredients', models.ManyToManyField(blank=True, to='blog.Ingredient')),
                ('special_labels', models.ManyToManyField(blank=True, to='blog.SpecialLabel')),
                ('traces', models.ManyToManyField(blank=True, to='blog.Trace')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.URLField(max_length=2048)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.shop')),
                ('supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.supplement')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('affiliate', models.BooleanField(default=False)),
                ('discount_code', models.CharField(blank=True, max_length=200)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('discount_unit', models.CharField(choices=[('shipping', 'Free Shipping'), ('discount', 'Euro Price discount'), ('2F1', 'Two for One')], max_length=100)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('discount_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('item', models.ManyToManyField(blank=True, to='blog.ShoppingItem')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.shop')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='supplement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.supplement'),
        ),
        migrations.AddField(
            model_name='content',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.unit'),
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('activeIngredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.activeingredient')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ingredient')),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.trace')),
            ],
        ),
        migrations.AddField(
            model_name='activeingredient',
            name='connection',
            field=models.ManyToManyField(blank=True, to='blog.Connection'),
        ),
        migrations.AddField(
            model_name='activeingredient',
            name='interactions',
            field=models.ManyToManyField(to='blog.ActiveIngredient'),
        ),
    ]
