# Generated by Django 3.2.16 on 2023-05-03 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_content_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.connection'),
        ),
    ]
