# Generated by Django 3.2.16 on 2023-03-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_vendor_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='Active',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='ingredient',
            new_name='active',
        ),
    ]
