# Generated by Django 3.2.16 on 2023-05-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_content_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeingredient',
            name='interactions',
            field=models.ManyToManyField(blank=True, to='blog.ActiveIngredient'),
        ),
    ]
