# Generated by Django 3.2.16 on 2023-05-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_activeingredient_interactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplement',
            name='daily_dose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
